---
# tasks file for ansible-role-rhel7-kvm-cloud-init

- name: Get a list of all instances
  virt:
    command: list_vms
  register: all_instances
  become: yes
  delegate_to: "{{ kvm_install_host }}"

- name: teardown the VM
  import_tasks: teardown-vm.yml
  become: yes
  delegate_to: "{{ kvm_install_host }}"
  when: vm_teardown|bool

- name: build the VM
  import_tasks: build.yml
  become: yes
  delegate_to: "{{ kvm_install_host }}"
  when: not vm_teardown|bool

- name: Refresh inventory to ensure new instances exist in inventory
  meta: refresh_inventory

- name: run post configuration
  import_tasks: post-config.yml
  become: yes
  when: not vm_teardown|bool
