---
- name: check for {{ vm_name }} in inventory {{ inventory_file }}
  command: grep {{ vm_name }} {{ inventory_file }}
  register: vm_in_inventory
  check_mode: no
  ignore_errors: yes
  changed_when: no
  when: update_inventory and vm_ip is defined

- name: scan remote for keys
  shell: |
      ssh-keyscan -H {{ vm_name }} \
                  {{ vm_ip }} \
                  {{ lookup('dig', vm_name ) }} | sort -u
  register: host_keys
  changed_when: false
  delegate_to: "{{ kvm_install_host }}"

- name: Update "~/.ssh/known_hosts" with discovered keys
  known_hosts:
    state: present
    name: "{{ item }}"
    key: "{{ host_keys.stdout_lines | select('search','^'~item~' .*$') | join('\n') }}"
  loop:
    - "{{ vm_name }}"
    - "{{ vm_ip }}"
    - "{{ lookup('dig', vm_name ) }}"
  failed_when: false
  delegate_to: "{{ kvm_install_host }}"

- name: update {{ vm_name }} /etc/resolv.conf
  template:
    src: resolv.conf.j2
    dest: /etc/resolv.conf
  when: ping_result is not failed
  delegate_to: "{{ vm_name }}"

- name: change root password
  user:
    name: root
    update_password: always
    password: "{{ kvm_vm_root_pwd | password_hash('sha512') }}"
  when: ping_result is not failed
  delegate_to: "{{ vm_name }}"

- name: ensure cloud-init is uninstalled
  yum:
    name: cloud-init
    state: absent
  when: ping_result is not failed
  delegate_to: "{{ vm_name }}"


  #- name: make sure resolv.conf is updated
  #  find:
  #    paths: /etc/
  #    contains: '^nameserver ([0-9]{1,3}\.){1,3}[0-9]{1,3}$'
  #    patterns: "resolv.conf"
  #  register: resolv_conf_entries
  #  delegate_to: "{{ vm_name }}"
  #  when: vm_in_inventory.rc == 0
  #
  #- name: check for dns lookup
  #  command: getent ahosts www.cnet.com
  #  failed_when: false
  #  changed_when: false
  #  register: dns_lookup_result
  #  delegate_to: "{{ vm_name }}"
  #  when: vm_in_inventory.rc == 0
