---
- name: START-UP-VM starting up {{ vm_name }}
  tags: [startup_vm]
  virt:
    name: "{{ vm_name }}"
    state: running

- name: CONFIGURE_VM check if {{ vm_name }} is reachable on known ip address
  tags: [startup_vm]
  wait_for:
    host: "{{ vm_ip }}"
    port: 22
    delay: 10
    timeout: 120
    msg: "{{ vm_name }} not reachable on {{ vm_ip }}"
  register: ping_result