#!/bin/bash

SCRIPT=$(basename "${BASH_SOURCE[0]}")

function HELP {
  echo -e " -a list all network details"
  echo -e " -p list ip"
  echo -e " -m list mac"
  echo -e " -i list network interface"
  echo -e " -n list network cidr"
  echo -e " -r return ip of given VM"
  echo -e " -e return ip of given network interface"
  exit 1
}

while getopts "apminhr:e:" opt
do
    case "$opt" in
      a) ALL=true;;
      p) IPADDR=true;;
      m) MACADDR=true;;
      i) NETIF=true;;
      n) CIDR=true;;
      r) VM=$OPTARG;;
      e) NETWORK_INTERFACE=$OPTARG;;
      h) HELP;;
      \?) echo -e "Usage: ${SCRIPT} [-a] [-i] [-m] [-n]";;
    esac
done
shift "$((OPTIND-1))"

CLI_USAGE () {
    for vm in $(virsh list | awk '/running/ {print $2}')
    do
        if [ "A${NETWORK_INTERFACE}" != "A" ]
        then
            RESULT=$(virsh domifaddr "$vm" --interface "${NETWORK_INTERFACE}" --source agent 2> /dev/null|grep -v 127 | grep -E "([0-9]{1,3}[\.]){3}[0-9]{1,3}")
        else
            RESULT=$(virsh domifaddr "$vm" --source agent 2> /dev/null|grep -v 127 | grep -E "([0-9]{1,3}[\.]){3}[0-9]{1,3}")
        fi
        
        IP=$(echo "${RESULT}" | grep -v 127 | grep -E -o "([0-9]{1,3}[\.]){3}[0-9]{1,3}")
        INTERFACE=$(echo "${RESULT}" | awk '{print $1}')
        MAC=$(echo "${RESULT}" | awk '{print $2}')
        NETWORK=$(echo "${RESULT}" | awk '{print $4}')
        if [ "A${IP}" != "A" ]
        then
            if [ "${ALL}" ]
            then
                printf '%-7s %4s %5s %5s %6s\n' "${vm}" "${IP}" "${INTERFACE}" "${MAC}" "${NETWORK}"
            fi

            if [ "${IPADDR}" ]
            then
                printf '%-7s\n' "${IP}"
            fi

            if [ "${MACADDR}" ]
            then
                printf '%-7s\n' "${MAC}"
            fi

            if [ "${NETIF}" ]
            then
                printf '%-7s\n' "${INTERFACE}"
            fi

            if [ "${CIDR}" ]
            then
                printf '%-7s\n' "${NETWORK}"
            fi

        fi
    done
}

ANSIBLE_USAGE () {
    if [ "A${NETWORK_INTERFACE}" != "A" ]
    then
        VM_IP=$(virsh domifaddr "${VM}" --interface "${NETWORK_INTERFACE}" --source agent 2> /dev/null|grep -v 127 | grep -E -o "([0-9]{1,3}[\.]){3}[0-9]{1,3}")
    else
        VM_IP=$(virsh domifaddr "${VM}" --source agent 2> /dev/null|grep -v 127 | grep -E -o "([0-9]{1,3}[\.]){3}[0-9]{1,3}")
    fi
    echo "${VM_IP}"
}

if [ "A${VM}" != "A" ]
then
    ANSIBLE_USAGE
else
    CLI_USAGE
fi

exit 0